### PR TITLE
Execute SDRA view to retrieve assessment data

### PR DESCRIPTION
**Pull request by Rossall82**
- Change SdocId type from complex type to int
- Increase columns lengths where appropriate in WorkflowDatabase
- Use AutoMapper to transform data into EF model classes
- Supporting methods to get assessment data within WorkflowCoordinator
- Refactor URI related config keys from GeneralConfig to the newly created UriConfig

### CODE REVIEW

**Comment by UKHOGreg** [comment]
Do we need to updated the swagger definition to reflect the change to sdocid type?

**Comment by UKHOGreg** [comment]
Can we update DatabaseDesign.md with the changes to the AssessmentData table?

**Comment by Rossall82** [comment]
> Do we need to update the swagger definition to reflect the change to sdocid type?

Done!

**Comment by Rossall82** [comment]
> Can we update DatabaseDesign.md with the changes to the AssessmentData table?

Done!

**Pull request merged**
